---
- name: test de conversion d une vm
  hosts:  localhost

  tasks:

    - name: lancer virt-v2v
      ansible.builtin.shell: |
        echo "configuration du fichier d'authentification"

        source /home/devops/admin-openrc.sh
        export LIBGUESTFS_BACKEND=direct
        /usr/bin/virt-v2v \
          -i vmx \
          -it ssh \
          "ssh://joel@192.168.222.1/home/joel/vmware/Attack/Attack.vmx" \
          -o local \
          -of qcow2 \
          -os /var/tmp/v1 \
          -v -x

      args:
        executable: /bin/bash
      ansible_verbosity=3
